title: Joselito
subtitle: Desenvolvedor
description: Aqui é o Joselito. Sou apaixonado pela web, organizador do GDG Recife e instrutor pela Tampa Works. Palestro sobre tecnologias web e gosto de F1, de aeroportos, de burritos e de piadas de baixa qualidade.
author: Joselito Júnior
language:
- pt-br
- en
timezone:

url: https://joselito.space
root: /
permalink: :title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: arquivos
category_dir: categorias
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

default_category: codigo
category_map:
tag_map:

date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: air-force-one

deploy:
  type: git
  repo: git@github.com:joselitojunior1/joselito.space.git
  branch: space

feed:
  type: rss2
  path: rss.xml
  limit: 20
  content: true

html_minifier:
  enable: true
  ignore_error: false
  exclude:

fbia:
  limit: 20
  path: fbia.xml

josenews: false
sininho: false